labels: ["status:from-qa"]
body:
  - type: textarea
    id: bug_report
    attributes:
      label: Reportar Bug
      description: Descreve o problema encontrado na Batalha Real
    validations:
      required: true
