#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 004-sync-failed-staging-2026-01-07

set -e

echo "========================================"
echo "Investigation Environment Setup"
echo "Staging Sync Workflow Failure (Issue #128)"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check GitHub CLI
if ! command -v gh &> /dev/null; then
    echo -e "${RED}GitHub CLI (gh) not found${NC}"
    echo "Install with: brew install gh"
    exit 1
fi
echo -e "${GREEN}✓ GitHub CLI installed${NC}"

# Check authentication
if ! gh auth status &> /dev/null; then
    echo -e "${YELLOW}GitHub CLI not authenticated${NC}"
    echo "Please run: gh auth login"
    exit 1
fi
echo -e "${GREEN}✓ GitHub CLI authenticated${NC}"

# ============================================
# INVESTIGATION SETUP
# ============================================

echo ""
echo "========================================"
echo "Investigation Workflow"
echo "========================================"
echo ""
echo "This is an INVESTIGATION task with the following phases:"
echo "  1. Reproduce & Document Failure"
echo "  2. Root Cause Analysis"
echo "  3. Implement Fix"
echo "  4. Verification & Prevention"
echo ""
echo "Key Investigation Steps:"
echo "  - Fetch logs from failed run #20772339098"
echo "  - Compare staging vs production workflows"
echo "  - Validate environment secrets"
echo "  - Document root cause in INVESTIGATION.md"
echo ""

# ============================================
# ACCESS TO FAILED RUN
# ============================================

echo "Testing access to failed workflow run..."
if gh run view 20772339098 --json status &> /dev/null; then
    echo -e "${GREEN}✓ Can access failed run #20772339098${NC}"
else
    echo -e "${YELLOW}⚠ Cannot access run #20772339098${NC}"
    echo "  You may need to authenticate with additional permissions"
fi

# ============================================
# ENVIRONMENT INFO
# ============================================

echo ""
echo "========================================"
echo "Environment Information"
echo "========================================"
echo ""
echo "Repository: bcamarneiro/adamastor"
echo "Failed Run: https://github.com/bcamarneiro/adamastor/actions/runs/20772339098"
echo "Issue: #128"
echo ""
echo "Workflow Files:"
echo "  - .github/workflows/sync-data.yml"
echo "  - .github/workflows/sync-photos.yml"
echo "  - .github/workflows/deploy-staging.yml"
echo ""
echo "Services Involved:"
echo "  - GitHub Actions (primary)"
echo "  - Watcher service (apps/watcher)"
echo ""

# ============================================
# USEFUL COMMANDS
# ============================================

echo "========================================"
echo "Useful Investigation Commands"
echo "========================================"
echo ""
echo "Fetch failed run logs:"
echo "  gh run view 20772339098 --log"
echo ""
echo "List recent sync workflow runs:"
echo "  gh run list --workflow=sync-data.yml --limit 10"
echo ""
echo "Check recent commits:"
echo "  git log --since='7 days ago' --oneline -- .github/workflows apps/watcher"
echo ""
echo "List staging environment secrets:"
echo "  gh secret list --env staging"
echo ""
echo "Manually trigger staging sync (for testing fix):"
echo "  gh workflow run sync-data.yml --ref staging -f environment=staging"
echo ""

# ============================================
# READY TO INVESTIGATE
# ============================================

echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}You can now begin the investigation.${NC}"
echo ""
echo "Next steps:"
echo "  1. Run: gh run view 20772339098 --log > failed-run-logs.txt"
echo "  2. Review the logs to identify the exact failure point"
echo "  3. Document findings in INVESTIGATION.md"
echo ""
